server:
  port: 8080
spring:
  application:
    name: yue-library-test
  profiles:
    include:
    - yue-library-data-jdbc
    - yue-library-data-redis
    active:
    - test-confidential
#    - test-confidential-performance

logging:
  level:
    ai.yue.library: debug